feat: first version of readme.
sern-handler/awesome-plugins pull request #38
Opened 2022-09-11 13:25 UTC by SrIzan10

PLEASE DO NOT MERGE THIS YET.

I made this on a phone and there is no styling whatsoever.

2022-09-11 20:03 UTC, SrIzan10 commented
oops sorry for not using the right conventional commit message at first 😩

2022-09-11 20:04 UTC, SrIzan10 commented
okay it's ready

2022-09-12 01:42 UTC, EvolutionX-10 requested changes
Add some awesome badges and mention that this is maintained by the _awesome_ community. and change all secondary headers from `###` to `##`

2022-09-12 04:58 UTC, SrIzan10 commented
will do later today

On Mon, 12 Sep 2022 at 3:42 AM, Evo ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Add some awesome badges and mention that this is maintained by the
> *awesome* community. and change all secondary headers from ### to ##
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sern-handler/awesome-plugins/pull/38#pullrequestreview-1103400231>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP646AQELPJCF7XVGQBTUZDV52DADANCNFSM6AAAAAAQJY5H44>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>
-- 
Desarrollador Fullstack y freelancer.
Correos: ***@***.*** y ***@***.***

2022-09-13 10:20 UTC, SrIzan10 commented
I didn't have time yesterday, let me finish it.

https://canary.discord.com/channels/889026545715400705/980390255574282282/1019178307155152999

also read that

2022-09-13 11:09 UTC, SrIzan10 commented
kay done, ready to merge

2022-09-13 13:21 UTC, EvolutionX-10 requested changes
See [this](https://github.com/sindresorhus/awesome/blob/main/awesome.md) as well, tyvm

2022-09-13 13:50 UTC, SrIzan10 commented
so we're applying for awesome right?

2022-09-13 13:58 UTC, SrIzan10 commented
sorry for not fixing `###` before. I'm using the Github Web Editor, got timed out while commiting and losing the work.

2022-09-14 08:44 UTC, SrIzan10 commented
@jacoobes please review?

2022-09-14 10:05 UTC, SrIzan10 commented
also, please enable server widgets so the discord badge can work

2022-09-14 12:47 UTC, EvolutionX-10 reviewed
Looks fine to me, server widget is enabled now, there are few things in my mind but I'll add them later. Let seren review it

2022-09-14 12:49 UTC, SrIzan10 commented
cool, thank you very much evo!
![image](https://user-images.githubusercontent.com/66965250/190158232-4be408fb-931a-444e-8174-246767a319d4.png)

2022-09-14 12:50 UTC, SrIzan10 commented
also, can you approve it? seems like the requested changes are still there!

2022-09-14 12:53 UTC, EvolutionX-10 approved these changes, later dismissed

2022-09-14 13:04 UTC, SrIzan10 commented
cool

2022-09-14 15:59 UTC, jacoobes requested changes

2022-09-14 15:59 UTC, jacoobes commented on README.md
> +Code it in typescript, and a GitHub Action will convert the plugin to JavaScript automatically when merged.
TypeScript, not typescript

2022-09-14 15:59 UTC, jacoobes commented on README.md
> +
Make a warning saying you must include sern.config.json!, if you are installing via cli

2022-09-14 16:00 UTC, SrIzan10 commented
will do

2022-09-14 16:36 UTC, SrIzan10 commented on README.md
> +Code it in typescript, and a GitHub Action will convert the plugin to JavaScript automatically when merged.
done

2022-09-14 16:37 UTC, SrIzan10 commented on README.md
> +
done

2022-09-14 16:39 UTC, jacoobes commented
cheers

2022-09-14 16:39 UTC, jacoobes approved these changes

2022-09-14 16:40 UTC, SrIzan10 commented
lets hope evo approves

2022-09-14 16:55 UTC, EvolutionX-10 approved these changes

2022-09-14 16:56 UTC, merged

2022-09-14 17:28 UTC, SrIzan10 commented
🎉 thanks!